# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build: docker
        ports:
            - 80:80
        volumes:
            - '.:/var/www/html/demo-docker-server'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        ports:
            - 3306:3306
        networks:
            - sail
networks:
    sail:
        driver: bridge
