version: '3'
services:
    app:
        build: docker
        ports:
            - 80:80
        volumes:
            - '.:/var/www/html/manager-server'
        networks:
            - manager
        depends_on:
            - mysql

    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        ports:
            - 3306:3306
        networks:
            - manager
networks:
    manager:
        driver: bridge